trigger:
- main

pool:
  name: Default

variables:
  ACR_NAME: orderflowacr123
  IMAGE_NAME: orderflow

steps:

- script: |
    python --version
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

- script: |
    docker build -t $(IMAGE_NAME):$(Build.BuildId) .
  displayName: 'Build Docker Image'

- script: |
    az acr login --name $(ACR_NAME)
  displayName: 'Login to ACR'

- script: |
    docker tag $(IMAGE_NAME):$(Build.BuildId) $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId)
  displayName: 'Tag Docker Image'

- script: |
    docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId)
  displayName: 'Push Image to ACR'

- script: |
    kubectl set image deployment/orderflow orderflow=$(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId) -n orderflow
    kubectl rollout status deployment/orderflow -n orderflow
  displayName: 'Deploy to AKS'